export const EXPORT_HEADER_AR: Record<string, string> = {
    fullName: 'الاسم الكامل',
    nationalId: 'الرقم القومي',
    religion: 'الديانة',
    gender: 'النوع',
    dateOfBirth: 'تاريخ الميلاد',
    placeOfBirth: 'مكان الميلاد',
    birthCity: 'مدينة الميلاد',
    phoneNumber: 'رقم الهاتف',
    telephone: 'التليفون',
    fullAddress: 'العنوان الكامل',
    isEgyptian: 'مصري',
    is_inside_egypt: 'داخل مصر',
    countryOfResidence: 'دولة الإقامة',
    passportIssuingCountry: 'دولة إصدار الجواز',
    governorateId: 'المحافظة',
    cityId: 'المدينة',
    policeDepartmentId: 'المركز / القسم',
    passportNumber: 'رقم الجواز',
    nationality: 'الجنسية',
    highSchoolEducationDistrictId: 'الإدارة التعليمية للثانوية',
    highSchoolFromEgypt: 'الثانوية من مصر',
    highSchoolTotalGrade: 'المجموع الثانوي',
    highSchoolCountry: 'دولة الثانوية',
    highSchoolGovernorate: 'محافظة الثانوية',
    qualificationId: 'المؤهل',
    is_new: 'طالب جديد',
    facultyId: 'الكلية',
    departmentId: 'القسم',
    admissionYear: 'سنة القبول',
    studentIdCode: 'كود الطالب',
    academicYear: 'السنة الدراسية',
    educationSystemType: 'نظام التعليم',
    totalAcademicGrade: 'المجموع الكلي',
    enrollmentStatus: 'حالة القيد',
    isFatherEgyptian: 'الأب مصري',
    fatherFullName: 'اسم الأب',
    fatherNationalId: 'الرقم القومي للأب',
    fatherOccupation: 'مهنة الأب',
    fatherPhone: 'هاتف الأب',
    fatherNationality: 'جنسية الأب',
    guardianName: 'اسم ولي الأمر',
    guardianRelationship: 'صلة ولي الأمر',
    guardianOccupation: 'مهنة ولي الأمر',
    guardianNationalId: 'الرقم القومي لولي الأمر',
    guardianPhoneNumber: 'هاتف ولي الأمر',
    guardianNationality: 'جنسية ولي الأمر',
    dormType: 'نوع السكن',
    requiresMeals: 'يحتاج وجبات',
    personal_image: "صورة شخصية للطالب",
    national_id_front: "صورة البطاقة الشخصية للطالب (الوجه الأمامي)",
    national_id_back: "صورة البطاقة الشخصية للطالب (الوجه الخلفي)",
    passport_image: "صورة جواز السفر للطالب",
    visa_or_residency_image: "صورة تأشيرة الدخول أو الإقامة للطالب (لغير المصريين)",
    pre_university_certificate: "شهادات ما قبل الجامعة",
    nomination_card_image: "صورة بطاقة الترشيح الصادرة من مكتب التنسيق",
    enrollment_proof_image: "صورة إثبات القيد الرسمي بالكلية",
    guardian_id_front: "صورة البطاقة الشخصية لولي الأمر (الوجه الأمامي)",
    guardian_id_back: "صورة البطاقة الشخصية لولي الأمر (الوجه الخلفي)",
    guardian_identity: "صورة مستند إثبات صلة ولي الأمر بالطالب",

};